global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'mysql_exporter'
    static_configs:
      - targets: ['mysql_exporter:9104']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
